# SPDX-FileCopyrightText: 2025 2025 Lukas Heindl
#
# SPDX-License-Identifier: MIT

name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: go
          package-name: fcgiwrap-go
          default-branch: main
          version-file: go.mod
          initial-version: 0.1.0
