# SPDX-FileCopyrightText: 2025 2025 Lukas Heindl
#
# SPDX-License-Identifier: MIT

name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: go
          token: ${{ secrets.GITHUB_TOKEN }}

      # Build and upload only if a release was created
      - name: Set up Go
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Go binary
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mkdir -p dist
          GOOS=linux GOARCH='amd64' go build -o dist/fcgiwrap-go-Linux-amd64

      - name: Upload Release Artifact (Binary)
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} dist/fcgiwrap-go-Linux-amd64
